### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by tech-freak** [ddrown/teensy-ntp#1]
thank you for sharing such an awesome project !
Is it possible to make one based on RTC module only ? instead of GPS module as it can't be used indoor 

Fetch time from internet to RTC when internet is available or set manually and serve it as local NTP server ?

**Comment by ddrown** [comment]
Synchronizing an RTC against remote NTP servers would be a very different project.  Have you considered using chrony on a raspberry pi?

**Comment by tech-freak** [comment]
Yes different project, yes i have tried it and the end goal is for pi only
I have internet issue and HassIO won't work without active internet connection as it fetch time from online NTP sever on boot
Don't want to use raspian so building local NTP server is only an option i have
