### ISSUE TITLE
Suggestion for small changes to GPS.cpp

### ISSUE THREAD

**Issue by joepasquariello** [ddrown/teensy-ntp#5]
Hi Dan. Very cool project. Starting from your code, I got it to work on Teensy 4.1 with a different GPS (Neo M9N), and I had to make a few small changes to GPS.cpp.

First, I added two new macros for the "GN" versions of the RMC and GGA messages, naming them "CODE2", as you had done GNZDA versus GPZDA. 

#define GPS_CODE2_RMC "GNRMC"
#define GPS_CODE2_GGA "GNGGA"

Second, after un-commenting the #define GPS_USES_RMC in settings.h, I modified the code that uses the GP macros to test for either the GP or GN macros.

  if (tmp.equals(GPS_CODE_RMC) || tmp.equals(GPS_CODE2_RMC)) {
    validCode = inTimeCode;
  } else if (tmp.equals(GPS_CODE_GGA) || tmp.equals(GPS_CODE2_GGA)) {

Third, at the bottom of decode(), I had to change the logic related to the checksum test to fix an issue where the comparison was failing if the checksum had a leading '0'. The issue is that when a string is created from the numeric parity_ variable, and it's value is less then 0x10, it will be a one-character string, such as '0', '1', ... 'F', and when that string is compared to the two-character string from the GPS message, the comparison fails. My solution was to convert the two-character string to a uint8_t, and do the comparison numerically, as shown below.

    uint8_t csum = strtoul( tmp.c_str(), NULL, 16 );
    validString = parity_ == csum;

Thanks for a great project. I'm digging in to the details of NTPClock and ClockPID.

**Comment by ddrown** [comment]
Thank you for your bug report, I've added fixes for both items
